name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build cerdito
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ vars.RUST_VERSION }}
      - name: Test
        run: cargo test
      - name: Build
        run: cargo build --release --locked
      - name: Package current compilation
        id: package-current
        run: |
          install -Dm755 "target/release/cerdito" "cerdito-${GITHUB_REF##*/}-${GITHUB_SHA}/cerdito"
          install -Dm644 "README.md" "cerdito-${GITHUB_REF##*/}-${GITHUB_SHA}/README.md"
          install -Dm644 "LICENSE" "cerdito-${GITHUB_REF##*/}-${GITHUB_SHA}/LICENSE"
          install -Dm644 "cerdito.toml" "cerdito-${GITHUB_REF##*/}-${GITHUB_SHA}/cerdito.toml"
          echo "version=${GITHUB_REF##*/}-${GITHUB_SHA}" >> $GITHUB_OUTPUT
      - name: Archive current compilation
        uses: actions/upload-artifact@v4
        with:
          name: "cerdito-${{ steps.package-current.outputs.version }}"
          path: "cerdito-${{ steps.package-current.outputs.version }}/"
      - name: Package tagged compilation
        id: package
        if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
        run: |
          install -Dm755 "target/release/cerdito" "cerdito-${GITHUB_REF##*/}/cerdito"
          install -Dm644 "README.md" "cerdito-${GITHUB_REF##*/}/README.md"
          install -Dm644 "LICENSE" "cerdito-${GITHUB_REF##*/}/LICENSE"
          install -Dm644 "cerdito.toml" "cerdito-${GITHUB_REF##*/}/cerdito.toml"
          tar cvJf "cerdito-${GITHUB_REF##*/}.tar.xz" "cerdito-${GITHUB_REF##*/}"
          echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
        with:
          files: "cerdito-${{ steps.package.outputs.version }}.tar.xz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
